##
# CSS compiling tools.
#
- name: CSS | Install rubygems package
  yum: pkg=rubygems state=installed
  tags: css

- name: RUBY | Install Bundler
  shell: gem install bundler

- name: PHP | XDebug
  yum: pkg={{ php_package }}-pecl-xdebug state=installed
  tags: ntp

- name: PHP | Add section to the xdebug.ini file if it is missing
  lineinfile: dest=/etc/php.d/xdebug.ini
    regexp='^[XDebug]'
    insertbefore=BOF
    line='[XDebug]'

- name: PHP | Set up xdebug.ini
  ini_file: dest=/etc/php.d/xdebug.ini
    section={{ item.0.section }}
    option={{ item.1.key }}
    value={{ item.1.val }}
    backup=yes
  with_subelements:
    - "{{ xdebug }}"
    - options
  notify:
    - restart php-fpm

