##
# CSS compiling tools.
#
- name: CSS | Install rubygems package
  yum: pkg=rubygems state=installed
  tags: css

- name: RUBY | Install Bundler
  shell: gem install bundler

- name: PHP | XDebug
  yum: pkg={{ php_package }}-pecl-xdebug state=installed
  tags: ntp