---
# file: roles/web-front/tasks/main.yml

  # Install nginx
  - name: Install nginx server
    yum: pkg=nginx state=installed

  # Nginx configuration files
  - name: nginx.conf
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  - name: upstream_phpcgi.conf
    template: src=upstream_phpcgi.conf.j2 dest=/etc/nginx/conf.d/upstream_phpcgi.conf
  - name: appcluster_upstream.conf
    template: src=appcluster_upstream.conf.j2 dest=/etc/nginx/conf.d/appcluster_upstream.conf
  - name: mime.types
    copy: src=mime.types dest=/etc/nginx/mime.types
  - name: mappings.conf
    copy: src=mappings.conf dest=/etc/nginx/conf.d/mappings.conf
  - name: drupal.conf
    copy: src=drupal.conf dest=/etc/nginx/conf.d/drupal.conf
  - name: fastcgi_drupal.conf
    copy: src=fastcgi_drupal.conf dest=/etc/nginx/conf.d/fastcgi_drupal.conf
  - name: php_fpm_status.conf
    copy: src=php_fpm_status.conf dest=/etc/nginx/conf.d/php_fpm_status.conf
  - name: Create sites-enabled directory
    file: state=directory path=/etc/nginx/sites-enabled
  - name: site definitions
    template: src=sites.conf.j2 dest=/etc/nginx/sites-enabled/sites.conf
    notify:
      - restart nginx
  - name: Ensure nginx is running now and on boot
    service: name=nginx state=started enabled=yes

# PHP version specific setup:
# Written as such since the following fails:
#  - include: "{{ php_package }}.yml"

  - include: "php53u.yml"
    when: php_package == "php53u"

  - include: "php55u.yml"
    when: php_package == "php55u"

# PHP configuration ini file
  - name: php-fpm www.conf
    template: src=www.conf.j2 dest=/etc/php-fpm.d/www.conf
  - name: Prepare php {{ php_ini_file }}
    lineinfile:
      dest={{ php_ini_file }}
      regexp='^[{{ item.section }}]'
      insertafter=EOF
      line='[{{ item.section }}]'
      create=True
      mode=644
    with_items: 
      - "{{ php }}"

  # PHP configuration files
  - name: Provision php {{ php_ini_file }}
    ini_file: dest={{ php_ini_file }}
      section="{{ item.0.section }}"
      option="{{ item.1.key }}"
      value="{{ item.1.val }}"
      backup=yes
    with_subelements:
      - "{{ php }}"
      - options
    notify:
      - restart php-fpm

# Nginx configs.

  # Set correct log rotates
  - name: Nginx logrotate
    copy: src=nginx dest=/etc/logrotate.d/nginx
  - name: Drupal logrotate
    copy: src=drupal dest=/etc/logrotate.d/drupal
  - name: PHP-FPM logrotate
    copy: src=php-fpm dest=/etc/logrotate.d/php-fpm
    notify:
      - restart rsyslog
