---
# file: roles/web-front/tasks/php55u.yml

# Install all php packages
- name: Install php-fpm
  yum: pkg={{ php_package }}-fpm state=present

- name: Ensure php-fpm is running now and on boot
  service: name=php-fpm state=started enabled=yes

- name: Install php packages
  yum: pkg={{ item }} state=present
  with_items:
    - "{{ php_package }}"
    - "{{ php_package }}-mysqlnd"
    - "{{ php_package }}-gd"
    - "{{ php_package }}-imap"
    - "{{ php_package }}-mbstring"
    - "{{ php_package }}-pear"
    - "{{ php_package }}-xml"
    - "{{ php_package }}-xmlrpc"
    - "{{ php_package }}-pdo"
    - "{{ php_package }}-devel"
    - "{{ php_package }}-dba"
    - "{{ php_package }}-mcrypt"
    - "{{ php_package }}-soap"
    - "{{ php_package }}-opcache"
    - "{{ php_package }}-pecl-jsonc"
    - "{{ php_package }}-pecl-memcache"
