---
# file: roles/varnish/defaults/main.yml
# varnish sysconfig
varnish_port: '80'
varnish_memory: '512M'
varnish_thread_pools: '4'
varnish_thread_pool_min: '100'
varnish_thread_pool_max: '1000'

# varnish default.vcl
varnish_backends:
  - name: web1
    host: 192.168.0.1
    port: 8080
ssl_ip_fix: false