

# the following is also set in web-front - required here for xdebug
php_package: php53u

xdebug:
 - section: XDebug
   options:
    - key: xdebug.remote_enable
      val: 1
    - key: xdebug.remote_handler
      val: dbgp 
    - key: xdebug.remote_connect_back
      val: 1
    - key: xdebug.remote_port
      val: 9000
    - key: xdebug.remote_autostart
      val: 0
    - key: xdebug.remote_log
      val: /var/log/xdebug.log

