##
# CSS compiling tools.
#
- name: CSS | Install rubygems package
  yum: pkg=rubygems state=installed
  tags: css

- name: RUBY | Install Bundler
  shell: gem install bundler

- name: Development packages
  yum: pkg={{ item }} state=installed
  with_items:
    - "{{ development_packages }}"

- name: PHP | XDebug
  yum: pkg={{ php_package }}-pecl-xdebug state=installed
  tags: ntp

- name: PHP | Add section to the xdebug.ini file if it is missing
  lineinfile: dest=/etc/php.d/15-xdebug.ini
    regexp='^[XDebug]'
    insertbefore=BOF
    line='[XDebug]'

- name: PHP | Set up xdebug.ini
  ini_file: dest=/etc/php.d/15-xdebug.ini
    section={{ item.0.section }}
    option={{ item.1.key }}
    value={{ item.1.val }}
    backup=yes
  with_subelements:
    - "{{ xdebug }}"
    - options
  notify:
    - restart php-fpm

# Install and configure MailHog.
- name: MAILHOG | Ensure mailhog install directory exists.
  file:
    path: "{{ mailhog_install_dir }}"
    owner: root
    group: root
    state: directory
    mode: 0755

- name: MAILHOG | Download MailHog binary.
  get_url:
    url: "{{ mailhog_binary_url }}"
    dest: "{{ mailhog_install_dir }}/mailhog"
    owner: root
    group: root
    mode: 0755

- name: MAILHOG | Install the daemonize package.
  yum: pkg=daemonize state=installed

- name: MAILHOG | Copy mailhog init script into place.
  copy:
    src: mailhog
    dest: /etc/init.d/mailhog
    owner: root
    group: root
    mode: 0755

- name: MAILHOG | Ensure mailhog is enabled and will start on boot.
  service: name=mailhog state=started enabled=yes

- name: MAILHOG | Install sSMTP.
  yum: pkg=ssmtp state=installed

- name: MAILHOG | Copy sSMTP configuration.
  template:
    src: ssmtp.conf.j2
    dest: /etc/ssmtp/ssmtp.conf
    owner: root
    group: root
    mode: 0644





