---
# file: roles/web-front/defaults/main.yml

# Define the PHP version
# Available version are: php53u, php55u
php_package: php55u

php_ini_file: /etc/php.d/zz_wunderkraut.ini

# PHP ini
php:
 - section: PHP
   options:
    - key: memory_limit
      val: 256M
    - key: realpath_cache_size
      val: 256K
    - key: realpath_cache_ttl
      val: 7200
    - key: max_execution_time
      val: 60
    - key: max_input_time
      val: 60
    - key: post_max_size
      val: 24M
    - key: upload_max_filesize
      val: 50M
    - key: max_file_uploads
      val: 20
    - key: allow_url_fopen
      val: On
    - key: display_errors
      val: Off
    - key: html_errors
      val: Off
 - section: DATE
   options:
    - key: date.timezone
      val: Europe/Helsinki
 - section: APC
   options: 
    - key: apc.shm_size
      val: 256M
    - key: apc.ttl
      val: 0
    - key: apc.user_ttl
      val: 7200
    - key: apc.stat
      val: 0
 - section: suhosin
   options:
     - key: suhosin.mail.protect
       val: 2
     - key: suhosin.filter.action
       val: 402
     - key: suhosin.log.syslog
       val: S_ALL & ~S_SQL
     - key: suhosin.post.max_vars
       val: 1000
     - key: suhosin.request.max_vars
       val: 1000
 - section: OPCACHE
   options:
    - key: opcache.memory
      val: 256
    - key: opcache.validate
      val: 0
    - key: opcache.revalidate_freq
      val: 0

fpm_user: 'nginx'
fpm_group: 'nginx'
fpm_pm_max_children: '50'
fpm_pm_start_servers: '15'
fpm_pm_min_spare_servers: '10'
fpm_pm_max_spare_servers: '35'
fpm_pm_max_requests: '500'

# Nginx
user: nginx
worker_processes: 4
default_port: 8080
nginx_sites:
  - hostname: local.matkavekka.fi local.matkavekka.com
    port: 8080 default_server
    docroot: /vagrant/docroot
    accesslog: true
    accesslog_params: main buffer=32k
    errorlog: true
    logprefix: local.matkavekka.x
    ssl: false
    sslproxy: false
    ssl_certificate: default.crt
    ssl_certificate_key: default.key
    include_drupal: true
    cdn: false
    nocdnhostname: www.wunder.io
    redirect: false
    redirecthost: https://www.wunder.io
upstream:
  - server: unix:/tmp/php-fpm.sock
loadbalancer: false
loadbalancers:
  - host: 127.0.0.1
    port: 8081
real_ip_from_varnish: 127.0.0.1
